### ISSUE TITLE
Error - Can't find user_key 

### ISSUE THREAD

**Issue by travisLilleberg** [projectblacklight/blacklight-access_controls#26]
Hello,

I'm building a new Blacklight app and I'm trying to get blacklight-access_controls working with our LDAP setup.

I'm getting this error: 
`undefined method 'user_key' for #<User> Did you mean? username`

![error](https://cloud.githubusercontent.com/assets/8809048/23167296/d36f1b32-f811-11e6-98db-5a28e12b187d.png)

It appears to be stemming from line 77 in enforcement.rb.
```
      def apply_user_permissions(permission_types, ability = current_ability)
        user = ability.current_user
/*77*/    return [] unless user && user.user_key.present?
        permission_types.map do |type|
         escape_filter(solr_field_for(type, 'user'), user.user_key)
        end                                                                               
      end   
```

I created the user model with the devise generator: `rails generate devise user`. Then I altered it to use username instead of email, and set up the devise_ldap_authenticatable gem.

**Model**
```
class User < ApplicationRecord
   devise :ldap_authenticatable, :trackable
   devise :timeoutable, :timeout_in => 60.minutes

   attr_accessor :username
 end
```

**Migration**
```
class AddUsernameToUsers < ActiveRecord::Migration[5.0]                                   
   def change                                                                              
     rename_column :users, :email, :username≈                                              
   end                                                                                     
 end
``` 

I can't find anything in the Devise docs regarding user_key. Should I add a user_key attribute to the model too? What does it do?

_Versions:_
- Blacklight-access_controls - 0.6.1
- Blacklight - 6.7.3
- Devise - 4.2.0
- Devise_LDAP_Authenticatable - 0.8.5
- Rails - 5.0.1

Thanks,

-- Travis Lilleberg

**Comment by cbeer** [comment]
I think you've removed too much from your `User` model. 

`User#user_key` is provided by a mixin generated into your model by this gem:

https://github.com/projectblacklight/blacklight-access_controls/blob/master/lib/blacklight/access_controls/user.rb

(I'd also expect your `User` model to include `Blacklight::User`, and, if this is for a spotlight application, `Spotlight::User` as well)

**Comment by travisLilleberg** [comment]
Yep, that was the problem. Thanks.
