### ISSUE TITLE
uninitialized constant Blacklight::AccessControls

### ISSUE THREAD

**Issue by cam156** [projectblacklight/blacklight-access_controls#5]
I seem to have missed a step.  When I go to the catalog I get a an error thrown:

On the line: include Blacklight::AccessControls::User

**Comment by jcoyne** [comment]
Can you provide more context? A backtrace perhaps?

**Comment by cam156** [comment]
@jcoyne Here is the back trace:

NameError - uninitialized constant Blacklight::AccessControls:
  activesupport (4.2.4) lib/active_support/dependencies.rb:533:in `load_missing_constant'
  activesupport (4.2.4) lib/active_support/dependencies.rb:184:in `const_missing'
   () Users/cam156/etd/etda/app/models/author.rb:12:in `<class:Author>'
   () Users/cam156/etd/etda/app/models/author.rb:1:in `<top (required)>'
  activesupport (4.2.4) lib/active_support/dependencies.rb:457:in `block in load_file'
  activesupport (4.2.4) lib/active_support/dependencies.rb:647:in `new_constants_in'
  activesupport (4.2.4) lib/active_support/dependencies.rb:456:in `load_file'
  activesupport (4.2.4) lib/active_support/dependencies.rb:354:in `require_or_load'
  activesupport (4.2.4) lib/active_support/dependencies.rb:494:in `load_missing_constant'
  activesupport (4.2.4) lib/active_support/dependencies.rb:184:in `const_missing'
  activesupport (4.2.4) lib/active_support/inflector/methods.rb:261:in `block in constantize'
  activesupport (4.2.4) lib/active_support/inflector/methods.rb:259:in `constantize'
  activesupport (4.2.4) lib/active_support/dependencies.rb:566:in `get'
  activesupport (4.2.4) lib/active_support/dependencies.rb:597:in `constantize'
  devise (3.5.2) lib/devise.rb:287:in `get'
  devise (3.5.2) lib/devise/mapping.rb:81:in `to'
  devise (3.5.2) lib/devise/mapping.rb:76:in `modules'
  devise (3.5.2) lib/devise/mapping.rb:93:in `routes'
  devise (3.5.2) lib/devise/mapping.rb:160:in `default_used_route'
  devise (3.5.2) lib/devise/mapping.rb:70:in `initialize'
  devise (3.5.2) lib/devise.rb:321:in `add_mapping'
  devise (3.5.2) lib/devise/rails/routes.rb:224:in `block in devise_for'
  devise (3.5.2) lib/devise/rails/routes.rb:223:in `devise_for'
   () Users/cam156/etd/etda/config/routes.rb:9:in `block in <top (required)>'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:434:in `eval_block'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:412:in `draw'
   () Users/cam156/etd/etda/config/routes.rb:1:in `<top (required)>'
  activesupport (4.2.4) lib/active_support/dependencies.rb:268:in `block in load'
  activesupport (4.2.4) lib/active_support/dependencies.rb:240:in `load_dependency'
  activesupport (4.2.4) lib/active_support/dependencies.rb:268:in `load'
  railties (4.2.4) lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
  railties (4.2.4) lib/rails/application/routes_reloader.rb:40:in `load_paths'
  railties (4.2.4) lib/rails/application/routes_reloader.rb:16:in `reload!'
  railties (4.2.4) lib/rails/application/routes_reloader.rb:26:in `block in updater'
  activesupport (4.2.4) lib/active_support/file_update_checker.rb:75:in `execute'
  railties (4.2.4) lib/rails/application/routes_reloader.rb:7:in `execute'
  railties (4.2.4) lib/rails/application/finisher.rb:81:in `block (2 levels) in <module:Finisher>'
  activesupport (4.2.4) lib/active_support/callbacks.rb:446:in `block in make_lambda'
  activesupport (4.2.4) lib/active_support/callbacks.rb:192:in `block in simple'
  activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
  actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:71:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
   () Users/cam156/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
   () Users/cam156/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
   () Users/cam156/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

**Comment by cam156** [comment]
@jcoyne @val99erie  Never mind... User error... I forgot to restart my server.
