### ISSUE TITLE
Allow for the ability to download a file

### ISSUE THREAD

**Issue by cam156** [projectblacklight/blacklight-access_controls#6]
As a index builder I would like the ability to specify that a user can have access to discover and read a record, but not download the contents of the record.

This would allow for the contents of a file to remain private while the metadata search and show view of the record would be available for anyone to see.

**Comment by val99erie** [comment]
cam156:  I think this story is done, but I wanted to give you a little time to play around with it before I close the story.

You should be able to invoke normal cancan calls to check permissions for SolrDocuments
```
render_download_link if can? :download, solr_doc
```

For objects that aren't SolrDocuments, you'll need to write your own rules in your cancan ability class
```
can :download, FinalSubmissionFile, submission: { author_id: author.id }
```
